version: 2

sources:
  - name: staging
    database: AIRBNB
    schema: RAW
    tables:
      - name: raw_hosts
        columns:
          - name: is_superhost
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 2
      - name: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
      - name: raw_reviews


      