version: 2

models:
  - name: dim_listings_hosts
    description: "dimension table for hosts and their listings"
    columns:
      - name: listing_id
        data_type: number
        description: "unique ID for Airbnb listings"


      - name: listing_url
        data_type: varchar
        description: "URL for listing on Airbnb"

      - name: name
        data_type: varchar
        description: "Listing name"

      - name: room_type
        data_type: varchar
        description: "Type of room"

      - name: minimum_nights
        data_type: number
        description: "minimum nights needed to be able to reserve"

      - name: price
        data_type: number
        description: "Price per night"

      - name: host_id
        data_type: number
        description: "Unique ID for host"

      - name: host_name
        data_type: varchar
        description: "Host name"

      - name: is_superhost
        data_type: varchar
        description: "A flag showing if the host is superhost or not"

      - name: created_at
        data_type: timestamp_ntz
        description: "Creation time"

      - name: updated_at
        data_type: timestamp_ntz
        description: "Last Update time"

  - name: dim_hosts
    description: "view for Airbnb hosts"
    columns:
      - name: host_id
        data_type: number
        description: "Unique ID for host"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('dem_listings')
              field: host_id
            
      - name: host_name
        data_type: varchar
        description: "Host name"

      - name: is_superhost
        data_type: varchar
        description: "A flag showing if the host is superhost or not"
        tests:
          - accepted_values:
              values: ['f',
                        't'
                      ]

      - name: created_at
        data_type: timestamp_ntz
        description: "Creation time"

      - name: updated_at
        data_type: timestamp_ntz
        description: "Last Update time"

  - name: dim_listings
    description: "view for listings"
    columns:
      - name: listing_id
        data_type: number
        description: "unique ID for Airbnb listings"
        tests: 
          - unique
          - not_null

      - name: listing_url
        data_type: varchar
        description: "URL for listing on Airbnb"

      - name: name
        data_type: varchar
        description: "Listing name"

      - name: room_type
        data_type: varchar
        description: "Type of room"
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel Room']
              severity: 'warn'

      - name: minimum_nights
        data_type: number
        description: "minimum nights needed to be able to reserve"

      - name: host_id
        data_type: number
        description: "Unique ID for host"
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts')
              field: host_id

      - name: price
        data_type: number
        description: "Price per nigt"

      - name: created_at
        data_type: timestamp_ntz
        description: ""

      - name: updated_at
        data_type: timestamp_ntz
        description: ""
